Enable prompt toolkit by default
DidierRLopes/GamestonkTerminal pull request #177
Opened 2021-03-15 07:46 UTC by comradesmith

Enable prompt toolkit by default. This feature was added in #142 and greatly improves the UX of the terminal.

If there are any downsides to enabling this lets discuss them here

2021-03-15 08:33 UTC, DidierRLopes commented
> Enable prompt toolkit by default. This feature was added in #142 and greatly improves the UX of the terminal.
> 
> If there are any downsides to enabling this lets discuss them here

The only downside of this feature as far as I could tell was the fact that I wasn't able to make it work cleanly with the plots in pred and ta menus. Hence why @aia added both USE_PROMPT_TOOLKIT and USE_ION as feature flags, so that it could be up to the user to select the features he wanted.

If we could make these work together we could enable both by default. @clothespin mentioned that that is possible, I believe he's attempting this. See https://github.com/DidierRLopes/GamestonkTerminal/pull/158#issuecomment-797368914

2021-03-15 08:34 UTC, DidierRLopes commented
See #174 that's what happens when both ION and PROMPT_TOOLKIT are set to True.

2021-03-15 08:35 UTC, comradesmith commented
> See #174 that's what happens when both ION and PROMPT_TOOLKIT are set to True.

Oh I see, sorry I missed that. In that case I will try to replicate this with my simpler PR #176, as that might be a good enough stopgap measure to get some of those UX improvements

2021-03-15 08:43 UTC, DidierRLopes commented
> > See #174 that's what happens when both ION and PROMPT_TOOLKIT are set to True.
> 
> Oh I see, sorry I missed that. In that case I will try to replicate this with my simpler PR #176, as that might be a good enough stopgap measure to get some of those UX improvements

Sounds good. On that basis should we close this PR?

2021-03-15 16:23 UTC, aia requested changes
Before enabling Prompt Toolkit by default, the conflicts with matplotlib Ion need to be resolved.

Non-blocking graphs are far more important than terminal completion.

2021-03-19 13:38 UTC, DidierRLopes commented
#190 addresses this. I'll close this on that basis.

2021-03-19 13:38 UTC, closed without merging