Made use of prawcore.exceptions.ResponseException
DidierRLopes/GamestonkTerminal pull request #194
Opened 2021-03-16 09:46 UTC by henrytdsimmons

Changed the reddit search functions to catch specific praw response exceptions rather than general exceptions.

2021-03-16 13:27 UTC, DidierRLopes requested changes
<img width="508" alt="Captura de ecrã 2021-03-16, às 13 24 22" src="https://user-images.githubusercontent.com/25267873/111316200-f3c6c200-865a-11eb-8234-cee717fd0f83.png">

Can you add a return after each of the print("") ? It would prevent to keep iterating through the loop! Thanks

2021-03-16 20:08 UTC, DidierRLopes requested changes
Break isn't enough because it will try to parse something, and if this condition happens that's related with API token, so you can just simply return directly.

Also, on the print(...) can you add a new line at the end, like print("...\n")

Just test with wrong reddit api keys and make sure that the user experience is good :) 

Thanks!

2021-03-16 20:41 UTC, DidierRLopes requested changes

2021-03-16 20:41 UTC, DidierRLopes commented on gamestonk_terminal/sentiment/reddit_api.py
> +        )
missing a return here

2021-03-16 20:41 UTC, DidierRLopes commented on gamestonk_terminal/sentiment/reddit_api.py
> +                break
and here

2021-03-17 10:51 UTC, henrytdsimmons commented
Should be done now. Sorry for needing so many iterations!

2021-03-17 12:10 UTC, DidierRLopes approved these changes

2021-03-17 12:10 UTC, merged

2021-03-17 12:10 UTC, DidierRLopes commented
No problem! Thanks for the contribution :)