Add Sentiment area under Comparison Analysis
DidierRLopes/GamestonkTerminal pull request #250
Opened 2021-03-21 20:54 UTC by DidierRLopes

The new commands allow:
<img width="282" alt="Captura de ecrã 2021-03-20, às 15 57 01" src="https://user-images.githubusercontent.com/25267873/111920559-97630880-8a87-11eb-8ebf-fc416dc9d727.png">

<img width="754" alt="Captura de ecrã 2021-03-20, às 15 57 06" src="https://user-images.githubusercontent.com/25267873/111920560-97fb9f00-8a87-11eb-8d94-fc6e4583446e.png">

Also, fixed a bug that was adding the main ticker to the list of similar companies when selecting one of the financials command.

2021-03-21 23:36 UTC, jmaslek requested changes
#ilikethecorrelations

2021-03-21 23:36 UTC, jmaslek commented on gamestonk_terminal/comparison_analysis/README.md
>  ```
usage: hcorr

2021-03-21 23:36 UTC, jmaslek commented on gamestonk_terminal/comparison_analysis/README.md
> +```
`usage: scorr`  ?

2021-03-21 23:38 UTC, DidierRLopes commented on gamestonk_terminal/comparison_analysis/README.md
> +```
Nice, thanks! Should be fixed now

2021-03-22 00:21 UTC, jmaslek commented
Another comment:  when I go to ca menu, the only options I see are get/select.  Not sure if you want more options at first (note I don't have polygon API).

I see the menu pop up after I do select/ but if I load AAPL, then I can just use (ie) `hcorr -s msft,amzn` without needing the select first (but that is not an option in help until I do select).

Either way  I think this can be merged.

2021-03-22 00:28 UTC, DidierRLopes commented
> Another comment: when I go to ca menu, the only options I see are get/select. Not sure if you want more options at first (note I don't have polygon API).
> 
> I see the menu pop up after I do select/ but if I load AAPL, then I can just use (ie) `hcorr -s msft,amzn` without needing the select first (but that is not an option in help until I do select).
> 
> Either way I think this can be merged.

Good call, I agree with that. I'll display all menu options on that basis!

The Polygon API is just if you want to use the "get" command, that gives similar companies.

2021-03-22 00:41 UTC, jmaslek commented
looks good to me!

2021-03-22 01:29 UTC, merged